config/routes.rb
Rails.application.routes.draw do

  root 'words#index'

  resources :page_links
  resources :pages
  resources :words
  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true, uniqueness: { message: "category exist" }
  has_many :pages_categories
  has_many :pages, through: :pages_categories
end

app/models/page.rb
require "open-uri"
require "nokogiri"

class Page < ActiveRecord::Base
  validates :url, presence: true, uniqueness: { message: "page url exist" }, url: true
  validates :body, presence: true
  has_many :pages_page_links
  has_many :page_links, through: :pages_page_links
  has_many :pages_categories
  has_many :categories, through: :pages_categories
  has_one :word
  after_create :get_page_content
  after_create :detect_category
  after_create :find_word
  after_create :create_translate
  after_create :find_links

  class << self
    def custom_create(u)
      self.create(url: u, body: generate_body(u))
    end

    def generate_body(u)
      url = URI.encode(u)
      page = Nokogiri::HTML(open(url))
      page.css("#mw-content-text").to_s
    end
  end

  def get_page_content
    url = URI.encode(self.url)
    @result_parsing_page ||= Nokogiri::HTML(open(url))
  end

  def detect_category
    page_categories = @result_parsing_page.css(".mw-normal-catlinks ul a")
    page_categories.each do |categ|
      self.categories.create(name: categ.text) unless self.find_or_create_category(categ.text)
    end
  end

  def find_or_create_category(category)
    categ = Category.where(name: category).first
    self.pages_categories.find_or_create_by(category: categ) unless categ == nil
  end

  def find_links
    links_in_page = @result_parsing_page.css("a")
    links_in_page.each do |link|
      full_link = self.enescape_link(link['href'])
      create_page_link_in_page(full_link, link.text) if check_link_format(full_link)
    end
  end

  def find_word
    content = @result_parsing_page.css("#mw-content-text p").first
    name = @result_parsing_page.css("#firstHeading").text
    content.children.each { |c| c.remove if c.name == 'b' }
    Word.create(definition: name.capitalize, content: content.text, page: self)
  end

  def create_page_link_in_page(full_link, link)
    self.page_links.create(url: full_link, name: link) unless self.find_or_create_page_link(full_link)
  end

  def find_or_create_page_link(link_address)
    page = PageLink.where(url: link_address).first
    self.pages_page_links.find_or_create_by(page_link: page) unless page == nil
  end

  def enescape_link(link)
    if link != nil
      encode_link = URI::unescape(link)
      if /^\/wiki\/[0-9a-zA-ZА-Яа-я_()-]+$/ === encode_link
        "https://#{ detect_domain }#{ encode_link }"
      elsif /^\/\/(ru|en).wikipedia.org\/wiki\/[0-9a-zA-ZА-Яа-я_()-]+$/ === encode_link
        "https:#{ encode_link }"
      elsif /https:\/\/(ru|en).wikipedia.org\/wiki\/[0-9a-zA-ZА-Яа-я_()-]+$/ === encode_link
        encode_link
      end
    end
  end

  def detect_domain
    Addressable::URI.parse(self.url).host
  end

  def check_link_format(url)
    /^https:\/\/(ru|en).wikipedia.org\/wiki\/[0-9a-zA-ZА-Яа-я_-]+$/ === url
  end

  def find_translate
    if detect_domain == "en.wikipedia.org"
      @translate = @result_parsing_page.css("div#p-lang li.interwiki-ru a")
    elsif detect_domain == "ru.wikipedia.org"
      @translate = @result_parsing_page.css("div#p-lang li.interwiki-en a")
    else
      @translate = nil
    end
  end

  def create_translate
    find_translate
    if @translate.first != nil
      translate_link = enescape_link(@translate.first['href'])
      if check_link_format(translate_link)
        self.translation = translate_link
        self.save
      end
    end
  end
end

app/models/page_link.rb
class PageLink < ActiveRecord::Base
  validates :name, presence: true
  validates :url, presence: true, uniqueness: { message: "link exist" }, url: true
  has_many :pages_page_links
  has_many :pages, through: :pages_page_links
  before_create :encoding_link
  after_create :parse_next_page

  def find_page
    page = Page.find_by_url(self.url)
  end

  def page_custom_create
    u = self.url
    Page.custom_create(u)
  end

  protected

    def encoding_link
      self.url = URI::unescape(self.url)
    end

    def parse_next_page
      id = self.id
      HardWorker.perform_async(id)
    end

end

app/models/pages_category.rb
class PagesCategory < ActiveRecord::Base
  belongs_to :page
  belongs_to :category
end

app/models/pages_page_link.rb
class PagesPageLink < ActiveRecord::Base
  belongs_to :page
  belongs_to :page_link
end

app/models/word.rb
class Word < ActiveRecord::Base
  validates :definition, presence: true, uniqueness: { message: "word exist" }
  validates :content, presence: true
  validates :page_id, presence: true
  belongs_to :page

  class << self
    def search(query)
      where("definition like ?", "%#{query}%")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: :show

  def index
    @categories = Category.all.order(:name).paginate(page: params[:page], per_page: 30)
  end

  def show
    @pages = @category.pages
  end

  protected

    def find_category
      @category = Category.find(params[:id])
    end

end

app/controllers/page_links_controller.rb
class PageLinksController < ApplicationController
  def index
    @pagelinks = PageLink.all
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :find_page, only: :show
  before_action :get_links_and_words, only: :show
  before_action :translate, only: :show
  before_action :word, only: :show

  def index
    @pages = Page.all
  end

  def show
    gon.links = @existing_pages.to_json
    gon.page = @page.to_json
    gon.word = @word.to_json
    gon.words = @words.to_json
    gon.arrayPageLinksPageAssociation = @links_to_page.to_json
  end

  protected

    def find_page
      @page = Page.find(params[:id])
    end

    def get_links_and_words
      @existing_pages = []
      @words  = []
      @links_to_page = {}
      @links = @page.page_links

      @links.each do |link|
        page = Page.find_by_url(link.url)
        @links_to_page[:"#{page.id}"] = page.page_links.ids unless page == nil
        @existing_pages << page unless page == nil
        @words << page.word unless page == nil
      end
    end

    def word
      @word = @page.word
    end

    def translate
      @translation = Page.find_by_url(@page.translation)
    end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  def index
    if params[:search]
     @words = Word.search(params[:search].mb_chars.capitalize).order("created_at ASC").paginate(page: params[:page], per_page: 30)
    else
     @words = Word.order("created_at ASC").paginate(page: params[:page], per_page: 30)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/page_links_helper.rb
module PageLinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/categories/_list_categories.html.haml
- categories.each do |category|
  %li
    = link_to category.name, category_path(category)

app/views/categories/index.html.haml
.container
  - @categories.each do |category|
    %li
      = link_to category.name, category_path(category)
  %ul.pagination.pagination_wrap
    = will_paginate @categories, :inner_window => 1, :outer_window => 0, :renderer => BootstrapPagination::Rails, :previous_label => '&larr;'.html_safe, :next_label => '&rarr;'.html_safe

app/views/categories/show.html.haml
.container
  - @pages.each do |page|
    %li= link_to page.word.definition, page_path(page)

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "../"} Thesaurus
    #navbar.collapse.navbar-collapse
      = form_tag(words_path, :method => "get", class: "navbar-form", id: "search-form") do
        .input-append
          = text_field_tag :search, params[:search], class: "form-control", placeholder: "Enter the word "
          %button.btn.btn-primary{:type => "submit"}
            Search
      .navbar-form.navbar-right
        = link_to "All categories", categories_path, class: "btn btn-primary"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DiplomaV3
    = include_gon
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    =render "layouts/header"
    = yield

app/views/page_links/index.html.haml
.container.container-link
  = @pagelinks.count

app/views/pages/_link_to_translate.html.haml
- if !translate.nil?
  = link_to "Translation", page_path(translate), class: "btn btn-warning translate-button"

app/views/pages/_page.html.haml
%div.container
  = @page.body.html_safe

app/views/pages/index.html.haml
.container
  - @pages.each do |page|
    %li.to-page
      = link_to PageLink.find_by_url(page.url).name, page_path(page) unless PageLink.find_by_url(page.url) == nil

app/views/pages/show.html.haml
.container
  .graph_with_links.container
    #container
      #graph
      #notes
  %a.show_links.btn.btn-primary{"aria-controls" => "collapseLinks", "aria-expanded" => "false", "data-toggle" => "collapse", :href => "#collapseLinks", :role => "button"}
    Links
  %a.show_links.btn.btn-primary{"aria-controls" => "collapsCategories", "aria-expanded" => "false", "data-toggle" => "collapse", :href => "#collapseCategories", :role => "button"}
    Categories

  = render "pages/link_to_translate", page: @page, translate: @translation

  #collapseLinks.collapse
    .well
      - @existing_pages.each do |link|
        %li.page-link
          = link_to PageLink.find_by_url(link.url).name, page_path(link.id)

  #collapseCategories.collapse
    .well
      = render 'categories/list_categories', categories: @page.categories

= render "pages/page"

app/views/words/index.html.haml
.container
  - @words.each do |word|
    %li.word
      %p
        =link_to word.definition, page_path(word.page_id)
        = word.content

  %ul.pagination.pagination_wrap
    = will_paginate @words, :inner_window => 1, :outer_window => 0, :renderer => BootstrapPagination::Rails, :previous_label => '&larr;'.html_safe, :next_label => '&rarr;'.html_safe